# POST http://localhost:3000/get-blog
# Content-Type: application/json

# {
#    "blog_id": "Horse-Blog-Horse-BlogHorse-BlogHorse-BlogPLiEb6HKIrEbPEEGeBJnB"
# }

POST http://localhost:3000/get-profile
Content-Type: application/json

{
   "username": "xyz"
}