# POST http://localhost:3000/get-blog
# Content-Type: application/json

# {
#    "blog_id": "Horse-Blog-Horse-BlogHorse-BlogHorse-BlogPLiEb6HKIrEbPEEGeBJnB"
# }

# POST http://localhost:3000/change-password
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NWUyNjJmN2ZhOGI0MzM5ZGFlZDZjOCIsImlhdCI6MTcwMjgyNTUxMX0.zqpcVG8SyTw9aoy6eZrrjvxHcWzmEmPnRAsmopVcTrM



POST http://localhost:3000/user-written-blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NWUyNjJmN2ZhOGI0MzM5ZGFlZDZjOCIsImlhdCI6MTcwNjUyODM3NH0.kPkDlWKZUp1G-0QoyTv_5EK6TCIr30Cs7jryWxAeOj4
Content-Type: application/json

{
   "page": 1,
   "draft": false

}

# GET http://localhost:3000/new-notification
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NWUyNjJmN2ZhOGI0MzM5ZGFlZDZjOCIsImlhdCI6MTcwNTY3MjA3OX0.ejj2ahKE5Ed3RAonT8QlzuAJxZ-oapgFNerbo4nR0jc

